import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import { cn } from "../lib/utils";
import { Footer } from "./_components/Footer";
import { Header } from "./_components/Header";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hbal Trbah",
  description: "Generated by Hbal Trbah",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased bg-background")}>
        <SessionProvider> {/* Wrap the application with SessionProvider */}
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 min-h-screen">
            <Header />
            <main>
              {children}
              <Toaster />
            </main>
            <Footer />
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}

